name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d | tr -d '\r' > deploy_key
        chmod 600 deploy_key

    - name: Deploy to VM
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        ssh -i deploy_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip
          cd /path/to/your/project
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo fuser -k 80/tcp || true
          nohup python app.py &
        EOF


